mongo:
  debug: false
  uri: mongodb://localhost:27017/lrf
mailer:
  host: smtp.ethereal.email
  port: 587
  secure: false # true for 465, false for other ports
  auth:
      user: account.user
      pass: account.pass
emails:
  sender: sender@somemail.com
  seller: seller@somemail.com
secret: Over-ride me, whith whatever, lalala!
super-user:
  mail: admin@lrf.ro
  pwd: admin